/*export const SELECT_PRODUCT = 'SELECT_PRODUCT';
export const FETCH_PRODUCT = 'FETCH_PRODUCT';
export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
export const BOOK_SELECTED = 'BOOK_SELECTED';
export const BOOK_SEARCH ='BOOK_SEARCH';
export const READ_PRODUCTS ='READ_PRODUCTS';*/
